### ISSUE TITLE
Gulp-Watch?

### ISSUE THREAD

**Issue by dharapvj** [blacksonic/angular2-babel-esnext-starter#23]
Hi @blacksonic, thanks for the great starter assembly without TS hassle!

I had one question... can we not add `gulp-watch` in the entire array of gulp assembly? 
Without the gulp-watch, the live-reload kind of has no use since the application never built any of my changes in first place.

e.g. Right now, if I change say the `boot.less` file, the application does not know and I must restart the gulp serve task for building the files again (or fire up one more terminal to `gulp client-stylesheet` job and then type `rs` in current gulp serve window)

**Comment by blacksonic** [comment]
hi,

the problem is that if you modify the stylesheet, the page doesnt get reloaded nor the server?

**Comment by dharapvj** [comment]
Hi,

Not the CSS file.. but rather the `.less` file. e.g. boot.less file. Any changes to file would need compilation to CSS, correct? It does not get compiled to css and yes, page does not get reloaded.

Same is true for `index.html` as well. Try changing the "title" tag.

**Comment by blacksonic** [comment]
that is correct, havent been added to gulp tasks, as i was focusing on the javascript part

**Comment by dharapvj** [comment]
True... that _is_ a more important aspect! :-)

May be I will try to give you a PR so that you can concentrate on more important aspects..
Thinking of using [Gulp-Livereload](https://github.com/vohof/gulp-livereload) or watch task.

**Comment by blacksonic** [comment]
added a watch task for the stylesheets

**Comment by blacksonic** [comment]
https://github.com/blacksonic/angular2-babel-esnext-starter/commit/7f0ec3435783468a497d3c7083918f9f04145870
