### ISSUE TITLE
How do the starter removes livereload script in the index.html?

### ISSUE THREAD

**Issue by aflext** [blacksonic/angular2-babel-esnext-starter#27]
Hi,i just wonder what's behind the process of `gulp dist` when the starter removes the `<script>(function(){document.write('<script src="http://'+window.location.hostname+':35729\/livereload.js" type="text\/javascript"><\/script>');}).call(this);</script>`.

**Comment by blacksonic** [comment]
It is solved by using the gulp-delete-lines package and it strips lines which contain /livereload/.
