### ISSUE TITLE
How do I replace KOA with Express ?

### ISSUE THREAD

**Issue by aflext** [blacksonic/angular2-babel-esnext-starter#44]
It seems there is a lot of dependencies of KOA..

**Comment by blacksonic** [comment]
It serves the static files and implements the authentication.

My plan is to get rid of the server side and implementa authentication with Auth0 and post storage with either Firebase or LocalStorage. That would make this problem obsolete.

**Comment by aflext** [comment]
@blacksonic  I copy the webpack and gulp config to create a project and the file structure is the same with the starter,but the  boot file is not bundled into the dist file only if i change the path of entry.boot to `jquery` which is installed via npm.


    // ./client/boot.js
    alret(1);

    // ./client/vendor.js
    import 'jquery';
    import 'angular-route'

    // this will ouput boot.js and vendor.js into dist file
    entry: {
        boot: 'jquery',
        vendor: ['jquery', 'angular-route']
    },

    // this will not
    entry: {
        boot: './client/boot.js',
        vendor: './client/vendor.js'
    }
